# Generated by Django 5.2.7 on 2025-10-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_fines_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
