# Generated by Django 5.2.7 on 2025-11-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_country_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
