# Generated by Django 5.2.7 on 2025-11-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_login_city_login_country_login_gender_login_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='house_number',
            field=models.CharField(blank=True, db_column='house_number', max_length=50, null=True, verbose_name='House_Number'),
        ),
    ]
