# Generated by Django 6.0.1 on 2026-01-17 22:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_login_house_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=50)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='User/Profile-image/')),
                ('account_status', models.CharField(default='Pending', max_length=20)),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='vechile_register',
            name='vechile_image',
            field=models.FileField(blank=True, db_column='vechile_image', upload_to='User/Vechile-image/', verbose_name='Vechile_Image'),
        ),
        migrations.AlterField(
            model_name='vechile_register',
            name='vechile_model',
            field=models.CharField(db_column='vechile_model', max_length=50, verbose_name='Vechile_Model'),
        ),
        migrations.AlterField(
            model_name='vechile_register',
            name='vechile_number',
            field=models.CharField(db_column='vechile_number', max_length=50, verbose_name='Vechile_Number'),
        ),
        migrations.AlterField(
            model_name='vechile_register',
            name='vechile_type',
            field=models.CharField(db_column='vechile_type', max_length=50, null=True, verbose_name='Vechile_Type'),
        ),
    ]
