# Generated by Django 5.2.7 on 2025-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('track_time', models.DateTimeField(blank=True, null=True)),
                ('direction_in_degree', models.FloatField(blank=True, null=True)),
                ('satellite', models.IntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('x_acceleration', models.FloatField(blank=True, null=True)),
                ('y_acceleration', models.FloatField(blank=True, null=True)),
                ('z_acceleration', models.FloatField(blank=True, null=True)),
                ('tilt', models.FloatField(blank=True, null=True)),
                ('impact', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField(blank=True, null=True)),
                ('balance_fuel', models.FloatField(blank=True, null=True)),
                ('hd_status', models.CharField(blank=True, max_length=20, null=True)),
                ('hd_size', models.FloatField(blank=True, null=True)),
                ('hd_balance', models.FloatField(blank=True, null=True)),
                ('ibutton1', models.CharField(blank=True, max_length=50, null=True)),
                ('message_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ignition', models.BooleanField(default=False)),
                ('gsm_signal', models.IntegerField(blank=True, null=True)),
                ('polling_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('ha', models.FloatField(blank=True, null=True)),
                ('hb', models.FloatField(blank=True, null=True)),
                ('panic', models.BooleanField(default=False)),
                ('fuel_bar', models.FloatField(blank=True, null=True)),
                ('over_speed', models.BooleanField(default=False)),
                ('analog', models.FloatField(blank=True, null=True)),
                ('seat_belt', models.BooleanField(default=False)),
                ('prev_value', models.FloatField(blank=True, null=True)),
                ('ec', models.CharField(blank=True, max_length=50, null=True)),
                ('tp', models.CharField(blank=True, max_length=50, null=True)),
                ('SD_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('SD_Status', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('Network_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_datetime', models.DateTimeField(blank=True, null=True)),
                ('immobilizer', models.BooleanField(default=False)),
                ('IN1', models.BooleanField(default=False)),
                ('IN2', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
