# Generated by Django 6.0.1 on 2026-01-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_gps_lat_alter_gps_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clientid', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=150, null=True)),
                ('unitno', models.CharField(max_length=50)),
                ('ignition', models.SmallIntegerField()),
                ('tracktime', models.DateTimeField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('gpsstatus', models.SmallIntegerField(blank=True, null=True)),
                ('direction', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('odometer', models.BigIntegerField(blank=True, null=True)),
                ('gpsodometer', models.BigIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('mainpower', models.FloatField(blank=True, null=True)),
                ('devbatterylevel', models.FloatField(blank=True, null=True)),
                ('panic', models.SmallIntegerField(blank=True, null=True)),
                ('immobalizer', models.SmallIntegerField(blank=True, null=True)),
                ('siren', models.SmallIntegerField(blank=True, null=True)),
                ('overspeed', models.FloatField(blank=True, null=True)),
                ('ha', models.CharField(blank=True, max_length=20, null=True)),
                ('hb', models.CharField(blank=True, max_length=20, null=True)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('fuellevel', models.FloatField(blank=True, null=True)),
                ('fuellevelltrs', models.FloatField(blank=True, null=True)),
                ('x_axis', models.FloatField(blank=True, null=True)),
                ('y_axis', models.FloatField(blank=True, null=True)),
                ('z_axis', models.FloatField(blank=True, null=True)),
                ('alerttype', models.CharField(blank=True, max_length=150, null=True)),
                ('driverid', models.CharField(blank=True, max_length=150, null=True)),
                ('driverrfid', models.CharField(blank=True, max_length=150, null=True)),
                ('drivername', models.CharField(blank=True, max_length=200, null=True)),
                ('alertdatetime', models.DateTimeField()),
                ('devicetype', models.CharField(blank=True, max_length=150, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'current_table',
                'managed': False,
            },
        ),
    ]
